// DeadCodePaths.java
// by Chuck Plater
// ab3189@wayne.edu
// cplater@me.com
//
// Term Paper Project for CSC 6110 Winter 2020
//
// Use soot to determine if there are any methods that exist but are not called
// using the callgraph generated by soot.
//
// TODO: When getting the methods, we should use a tuple to store the class name and the line number
//       to be used when reporting potential dead code paths.

package deadCodePaths;

import soot.*;
import soot.jimple.infoflow.android.*;
import soot.jimple.toolkits.callgraph.*;
import java.util.*;

public class DeadCodePaths {

	
	public static void main(String[] args) {
		
		String androidPlatformPath = "/Users/cplater/Developer/android-platforms";
		String appPath = "/Users/cplater/Documents/School/202001 Winter 2020/CSC 6110 Software Engineering/Homework 1/apks/two.apk";

		if (args.length == 2) {
			androidPlatformPath = args[0];
			appPath = args[1];
		}
		
		SetupApplication app = new SetupApplication(androidPlatformPath,appPath);
		
		app.constructCallgraph();
		
		// Create a list to store the method names
		List<String> availableMethods = new ArrayList<String>();
		
		for (SootClass entryPoint : app.getEntrypointClasses()) {
			for (SootMethod methods : entryPoint.getMethods()) {
				// Check to see if the method has already been added to the list
				if (! availableMethods.contains(methods.getName())) 
					// Add the method to the list if it is new
					availableMethods.add(methods.getName());
				}
		}
		CallGraph appCallGraph = Scene.v().getCallGraph();
		for (Edge edge : appCallGraph) {
			if (app.getEntrypointClasses().contains(edge.getTgt().method().getDeclaringClass())) {
				// remove target methods (they're getting called)
				if (availableMethods.contains(edge.getTgt().method().getName())) {
					availableMethods.remove(edge.getTgt().method().getName());
				}
				// remove source methods (they're doing the calling)
				if (availableMethods.contains(edge.getSrc().method().getName())) {
					availableMethods.remove(edge.getSrc().method().getName());
				}
			}
		}
		// Output the unused methods
		for (String method : availableMethods) {
			System.out.print(method);
			System.out.print(" not found in call graph\n");
		}
	}
}
